// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

#include "hal.h"
#include "mongoose/mongoose_glue.h"

static struct mg_fs *s_fs = &mg_fs_posix;
static const char *s_dir = "/tmp";

bool my_check_delete(void) {
  return false;  // File deletion is never in progress
}
void my_start_delete(struct mg_str params) {
  char path[256];
  struct mg_str name = mg_json_get_tok(params, "$.name");
  if (name.len >= 2 && name.buf[0] == '"') name.len -= 2, name.buf++;
  mg_snprintf(path, sizeof(path), "%s/%.*s", s_dir, name.len, name.buf);
  MG_DEBUG(("Deleting file: [%s]", path));
  s_fs->rm(path);
}

bool my_get_files(struct files *data, size_t i) {
  char buf[256] = "";  // Important: initialise to empty
  while (mg_fs_ls(s_fs, s_dir, buf, sizeof(buf))) {
    char path[sizeof(buf) + 20];
    size_t size = 0;
    mg_snprintf(path, sizeof(path), "%s/%s", s_dir, buf);
    //MG_DEBUG(("FILE: [%s]", path));
    if (i-- == 0) {
      s_fs->st(path, &size, NULL);
      mg_snprintf(data->name, sizeof(data->name), "%s", buf);
      data->size = (int) (long) size;
      return true;
    }
  }
  return false;
}

size_t my_file_read_fs(char *name, size_t offset, void *buf, size_t len) {
  char path[256];
  struct mg_fd *fd;
  mg_snprintf(path, sizeof(path), "%s/%s", s_dir, name);
  fd = mg_fs_open(s_fs, path, MG_FS_READ);
  MG_INFO(("path: %s, ofs: %lu, buf: %p, len: %lu", path, offset, buf, len));
  if (fd != NULL) {
    fd->fs->sk(fd->fd, offset);
    len = fd->fs->rd(fd->fd, buf, len);
    mg_fs_close(fd);
  } else {
    len = 0;
  }
  return len;
}
bool my_file_write_fs(char *name, size_t offset, void *buf, size_t len) {
  char path[256];
  struct mg_fd *fd;
  mg_snprintf(path, sizeof(path), "%s/%s", s_dir, name);
  fd = mg_fs_open(s_fs, path, MG_FS_WRITE);
  MG_INFO(("path: %s, ofs: %lu, buf: %p, len: %lu", path, offset, buf, len));
  if (fd != NULL) {
    fd->fs->sk(fd->fd, offset);
    fd->fs->wr(fd->fd, buf, len);
    mg_fs_close(fd);
  }
  return true;
}

int main(void) {
  // Cross-platform hardware init
  hal_init();
  MG_INFO(("HAL initialised, starting firmware..."));

  // This blocks forever. Call it at the end of main(), or in a
  // separate RTOS task. Give that task 8k stack space.
  mongoose_init();

  s_fs->mkd(s_dir);
  mongoose_set_http_handlers("delete", my_check_delete, my_start_delete);
  mongoose_set_http_handlers("files", my_get_files, NULL);
  mongoose_set_http_handlers("fs", my_file_read_fs, my_file_write_fs);

  for (;;) {
    mongoose_poll();
  }

  return 0;
}
